# Generated by Django 4.1.6 on 2023-03-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_avto_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
