# Generated by Django 4.1.6 on 2023-03-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='text',
        ),
    ]
